# Generated by Django 6.0.5 on 2026-05-17 18:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IOC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(db_index=True, max_length=2048)),
                ('ioc_type', models.CharField(choices=[('ip', 'IP Adresi'), ('domain', 'Domain'), ('url', 'URL'), ('hash', 'Dosya Hash'), ('email', 'Email')], db_index=True, max_length=10)),
                ('threat_score', models.IntegerField(default=0)),
                ('severity', models.CharField(choices=[('safe', 'Güvenli'), ('suspicious', 'Şüpheli'), ('malicious', 'Tehlikeli')], default='safe', max_length=12)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('country_code', models.CharField(blank=True, default='', max_length=5)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('isp', models.CharField(blank=True, default='', max_length=255)),
                ('asn', models.CharField(blank=True, default='', max_length=50)),
                ('abuseipdb_data', models.JSONField(blank=True, default=dict)),
                ('virustotal_data', models.JSONField(blank=True, default=dict)),
                ('alienvault_data', models.JSONField(blank=True, default=dict)),
                ('shodan_data', models.JSONField(blank=True, default=dict)),
                ('greynoise_data', models.JSONField(blank=True, default=dict)),
                ('ipinfo_data', models.JSONField(blank=True, default=dict)),
                ('urlhaus_data', models.JSONField(blank=True, default=dict)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_queried', models.DateTimeField(auto_now=True)),
                ('query_count', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'IOC',
                'verbose_name_plural': 'IOCs',
                'ordering': ['-last_queried'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ioc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.ioc')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queried_at', models.DateTimeField(auto_now_add=True)),
                ('sources_queried', models.JSONField(default=list)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('ioc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_logs', to='core.ioc')),
            ],
            options={
                'ordering': ['-queried_at'],
            },
        ),
        migrations.AddField(
            model_name='ioc',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='iocs', to='core.tag'),
        ),
        migrations.AddIndex(
            model_name='ioc',
            index=models.Index(fields=['ioc_type', 'threat_score'], name='core_ioc_ioc_typ_0c0b21_idx'),
        ),
    ]
