# Generated by Django 6.0.4 on 2026-05-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ioc',
            name='whois_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
